# Generated by Django 2.0.1 on 2018-02-02 16:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='games',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
    ]
