# Generated by Django 2.0.1 on 2018-02-04 18:29

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tournaments', '0002_tournaments_game_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournaments',
            name='game_uuid',
            field=models.UUIDField(choices=[('dalm', uuid.UUID('184fb5ed-789a-4058-8605-88564074e749')),
                                            ('фвы', uuid.UUID('bd8901da-51bb-4efb-9154-153d0f574974')),
                                            ('asf', uuid.UUID('7b3bc1b8-e180-4102-893d-8ceb6d0e15fa')),
                                            ('tourn', uuid.UUID('fa74bfe8-424b-4554-8f2b-73aff21f1055'))],
                                   verbose_name='Игра'),
        ),
    ]
