# Generated by Django 2.0.1 on 2018-02-07 16:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsTournamentsMatching',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.UUID('e2b8e1b8-5ab8-44dd-8ec7-d99c3f72d90b'), editable=False,
                                          verbose_name='UUID')),
                ('tournament_uuid', models.UUIDField(verbose_name='Турнир')),
                ('team_uuid', models.UUIDField(verbose_name='Команда')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='teams',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e2b8e1b8-5ab8-44dd-8ec7-d99c3f72d90b'), editable=False,
                                   verbose_name='UUID'),
        ),
    ]
