# Generated by Django 2.0.1 on 2018-02-05 21:10

import uuid

from django.db import migrations, models

import api_v0_1.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('logo',
                 models.ImageField(blank=True, upload_to=api_v0_1.models.logo_directory_path, verbose_name='Логотип')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан в')),
                ('tournament_uuid', models.UUIDField(
                    choices=[(uuid.UUID('82f5b831-2846-4809-abc0-942194df5edf'), 'tourn'),
                             (uuid.UUID('cc8ea866-2752-48a2-b43d-13a14ddb24e1'), 'asdflk'),
                             (uuid.UUID('2b270657-2a89-429b-9f5a-62ce6ff47397'), 'knsd'),
                             (uuid.UUID('2c7afc80-5294-459e-8238-45ef5fb19c6a'), 'sadf'),
                             (uuid.UUID('01e5223a-f03a-415b-b5d3-e31997b57c82'), 'sdfmk'),
                             (uuid.UUID('c56c2694-bb1c-4a4a-b426-9e36a7c1af5c'), 'sdgf'),
                             (uuid.UUID('7d27acb4-db6b-491f-bfb5-8a650a41fd06'), 'weoijr'),
                             (uuid.UUID('8bfdfcb9-46c8-45c7-b19e-20b9a7f49521'), 'akjns'),
                             (uuid.UUID('3683596c-30c7-4d7e-864b-14ca0e210fef'), 'zvxc\\'),
                             (uuid.UUID('64f317f4-67e4-42e0-866b-1e462460fa12'), 'qwre'),
                             (uuid.UUID('3bb1e667-1219-4f24-bfba-b3c0da99fc68'), 'ior'),
                             (uuid.UUID('0ba92f39-d7d1-46b5-acfc-af6c5b031574'), 'iuhfd'),
                             (uuid.UUID('593eafa2-6e33-4b34-a245-ab6b2b9e5a7d'), 'tyf'),
                             (uuid.UUID('5a0af5ae-d86c-40a1-9f94-b5298011fa88'), 'as;lfd'),
                             (uuid.UUID('384fcd78-8852-47fb-91c9-3c756e4cdbba'), 'as;lsfad'),
                             (uuid.UUID('77cd042e-7f66-4bfc-b26e-f3d04713860b'), 'lkdsf'),
                             (uuid.UUID('964159a5-ebee-4c50-8d31-89a3b3a182e2'), 'najknd'),
                             (uuid.UUID('5705057d-a771-4e44-afea-feba2bd9de57'), 'gamr')], verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'abstract': False,
            },
        ),
    ]
