# Generated by Django 2.0.1 on 2018-02-07 16:40

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('matches', '0002_auto_20180207_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e2b8e1b8-5ab8-44dd-8ec7-d99c3f72d90b'), editable=False,
                                   verbose_name='UUID'),
        ),
    ]
